using System.Collections;
using System.Collections.Generic;
using RosMessageTypes.Std;
using Unity.Robotics.ROSTCPConnector;
using UnityEngine;
using UnityEngine.SceneManagement;

public class SimulationManager : MonoBehaviour
{
    [System.Serializable] 
    public class NamedPrefab
    {
        public string name;
        public GameObject prefab;
    }
    [SerializeField]
    public string unitySystemIP = "127.0.0.1";
    public string[] environmentSceneNames;
    public NamedPrefab[] interfaces;
    
    public bool loadOnStart = true;
    
    string activeEnvironmentName;
    string activeInterfaceName;


    private ROSConnection ros;
    private GameObject activeInterface;
    private bool firstUpdate = true;
    bool lastLatch = false;
    
    // Start is called before the first frame update
    void Start()
    {
        ros = ROSConnection.GetOrCreateInstance();
        ros.RegisterPublisher<StringMsg>("unity/ip", latch: true);
        ros.RegisterPublisher<StringMsg>("trial/dash");
        ros.RegisterPublisher<StringMsg>("/task/error");
        ros.RegisterPublisher<BoolMsg>("/task/end");
        
        if (loadOnStart)
        {
            LoadEnvironmentScene(0);
            LoadInterfaceScene(0);
        }
        // HTTPDash.Instance.RegisterButton("Reset", () =>
        // {
        //     Debug.Log("Reset button clicked from HTTP!");
        //     ResetCurrentEnvironment();
        //     Destroy(activeInterface);
        //     LoadInterfaceScene(0);
        // });
       
        ros.Subscribe<BoolMsg>("/haptic/latched", msg =>
        {
            if (msg.data != lastLatch)
            {
                HTTPDash.Instance.SendNotification("Haptics", $"Device {(msg.data ? "latched":"unlatched")}", msg.data ? "blue" : "red");
            }
            lastLatch = msg.data;
        });
        ros.RegisterPublisher<BoolMsg>("/ui/show_hints");
        HTTPDash.Instance.RegisterButton("End Task", "End",  s => ros.Publish("/task/end", new BoolMsg(true)));
        HTTPDash.Instance.RegisterButton("Bedhead Collision", "Mark", (string s) =>
        {
            ros.Publish("/task/error", new StringMsg("bedhead_collision"));
            HTTPDash.Instance.SendNotification("Error Logged", $"Bedhead Collision", "orange");
        });

        HTTPDash.Instance.RegisterButton("Unplug Fail", "Mark", (string s) =>
        {
            ros.Publish("/task/error", new StringMsg("unplug_fail"));
            HTTPDash.Instance.SendNotification("Error Logged", $"Unplug Fail", "orange");
        });
        
        HTTPDash.Instance.RegisterButton("Plug Fail", "Mark", (string s) =>
        {
            ros.Publish("/task/error", new StringMsg("plug_fail"));
            HTTPDash.Instance.SendNotification("Error Logged", $"Plug Fail", "orange");
        });
        
        HTTPDash.Instance.RegisterButton("Environment Collision", "Mark", (string s) =>
        {
            ros.Publish("/task/error", new StringMsg("environment_collision"));
            HTTPDash.Instance.SendNotification("Error Logged", $"Environment Collision", "orange");
        });
        
        HTTPDash.Instance.RegisterButton("Pick Fail", "Mark", (string s) =>
        {
            ros.Publish("/task/error", new StringMsg("pick_fail"));
            HTTPDash.Instance.SendNotification("Error Logged", $"Pick Fail", "orange");
        });
        
        HTTPDash.Instance.RegisterButton("Place Fail", "Mark", (string s) =>
        {
            ros.Publish("/task/error", new StringMsg("place_fail"));
            HTTPDash.Instance.SendNotification("Error Logged", $"Place Fail", "orange");
        });
    }
    
    private int count = 0;
    
    public void ResetCurrentEnvironment()
    {
        StartCoroutine(ResetEnvironmentCoroutine());
    }

    private IEnumerator ResetEnvironmentCoroutine()
    {
        TaskEnvironment.instances.Remove(TaskEnvironment.instances[TaskEnvironment.currentIndex]);
        AsyncOperation unloadOp = SceneManager.UnloadSceneAsync(activeEnvironmentName);
        if (unloadOp != null)
        {
            while (!unloadOp.isDone)
                yield return null;
        }

        LoadEnvironmentScene(0);
    }

    public void LoadInterfaceScene(int sceneIndex)
    {
        this.activeInterfaceName = interfaces[sceneIndex].name;
        this.activeInterface = Instantiate(interfaces[sceneIndex].prefab, new Vector3(0, 100, 0), Quaternion.identity);
    }

    public void LoadEnvironmentScene(int sceneIndex)
    {
        this.activeEnvironmentName = environmentSceneNames[sceneIndex];
        for (int i = 0; i < TaskEnvironment.instances.Count; i++)
        {
            if (this.activeEnvironmentName.Equals(TaskEnvironment.instances[i]))
            {
                TaskEnvironment.currentIndex = i;
                break;
            }
        }
        HTTPDash.Instance.SendNotification("Scene Loaded", "Loaded scene: " + activeEnvironmentName, "blue");
        SceneManager.LoadScene(activeEnvironmentName, LoadSceneMode.Additive);
    } 
    

    // Update is called once per frame
    void Update()
    {
        if (firstUpdate)
        {
            ros.Publish("unity/ip", new StringMsg(unitySystemIP));
            firstUpdate = false;
        }
    }
}
